# backend/app/recon/services/report_service.py
"""HTML + PDF report generation for completed scans.

Reports are built from the persisted ScanResult rows associated with a
scan.  All target-controlled content is escaped via ``html.escape`` so
malicious HTML / scripts in scanned banners or response headers cannot
execute when the report is opened in a browser or PDF viewer.
"""
from __future__ import annotations

import base64
import html
import io
import os
import uuid
from datetime import datetime, timezone
from typing import Dict, Any, List, Optional

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.logging import logger
from app.recon.models.scan import Scan
from app.recon.models.scan_result import ScanResult
from app.recon.repositories.scan_repository import ScanRepository, ScanResultRepository
from app.repositories.user_repository import UserRepository


class ReportService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.scan_repo = ScanRepository(db)
        self.result_repo = ScanResultRepository(db)
        self.user_repo = UserRepository(db)

    # ------------------------------------------------------------------
    async def _get_username(self, user_id: int) -> str:
        """Fetch the username for a user_id.  Returns 'Unknown' if the user
        no longer exists (e.g. deleted after the scan was created)."""
        user = await self.user_repo.get_user_with_role(user_id)
        return user.username if user else "Unknown"

    # ------------------------------------------------------------------
    async def _gather(self, scan_id: int) -> tuple[Scan | None, List[ScanResult]]:
        scan = await self.scan_repo.get_scan_with_results(scan_id)
        if not scan:
            return None, []
        # Sort results by created_at
        results = sorted(scan.results, key=lambda r: r.created_at)
        return scan, results

    # ---- HTML ----------------------------------------------------------
    async def generate_html(self, scan_id: int) -> str | None:
        scan, results = await self._gather(scan_id)
        if not scan:
            return None

        report_id = uuid.uuid4().hex
        now = datetime.now(timezone.utc)
        grouped = self._group_results(results)
        summary = self._build_summary(scan, grouped)
        generated_by = await self._get_username(scan.user_id)

        parts: List[str] = []
        parts.append("<!DOCTYPE html>")
        parts.append("<html lang='en'><head><meta charset='utf-8'>")
        parts.append("<meta name='viewport' content='width=device-width, initial-scale=1'>")
        parts.append(f"<title>Basir Recon Report — {html.escape(scan.target)}</title>")
        parts.append("<style>")
        parts.append(self._html_css())
        parts.append("</style></head><body>")

        # Cover / header
        parts.append("<header class='cover'>")
        parts.append("<div class='brand'>Basir Security Management System</div>")
        parts.append("<h1>Network Reconnaissance Report</h1>")
        parts.append(f"<div class='meta'>Report ID: <code>{report_id}</code></div>")
        parts.append(f"<div class='meta'>Target: <code>{html.escape(scan.target)}</code></div>")
        parts.append(f"<div class='meta'>Scan ID: #{scan.id}</div>")
        parts.append(f"<div class='meta'>Generated by: <strong>{html.escape(generated_by)}</strong></div>")
        parts.append(f"<div class='meta'>Generated: {now.isoformat(timespec='seconds')}</div>")
        parts.append(f"<div class='meta'>Status: <span class='badge {scan.status.lower()}'>{scan.status}</span></div>")
        parts.append("</header>")

        # Executive summary
        parts.append("<section>")
        parts.append("<h2>Executive Summary</h2>")
        parts.append(f"<p>{html.escape(summary)}</p>")
        parts.append(self._summary_stats_html(scan, grouped))
        parts.append("</section>")

        # Target info
        parts.append("<section>")
        parts.append("<h2>Target Information</h2>")
        parts.append(self._target_info_html(scan))
        parts.append("</section>")

        # Host discovery
        if grouped["host_discovery"]:
            parts.append("<section>")
            parts.append("<h2>Host Discovery</h2>")
            parts.append(self._table_html(
                ["Host", "IP", "Hostname", "Status", "Latency (ms)"],
                [[html.escape(str(h.get("host"))), html.escape(str(h.get("ip") or "")),
                  html.escape(str(h.get("hostname") or "")),
                  html.escape(str(h.get("status") or "")),
                  html.escape(str(h.get("latency_ms") or ""))] for h in grouped["host_discovery"]]
            ))
            parts.append("</section>")

        # Ports
        if grouped["port_scan"]:
            parts.append("<section>")
            parts.append("<h2>Open Ports</h2>")
            rows = []
            for ps in grouped["port_scan"]:
                for port_entry in self._iter_port_scan_results(ps):
                    if port_entry.get("state") == "open":
                        rows.append([
                            str(port_entry.get("port")), html.escape(str(port_entry.get("protocol") or "tcp")),
                            html.escape(str(port_entry.get("state") or "")),
                            html.escape(str(port_entry.get("service_guess") or "")),
                            html.escape(str(port_entry.get("version") or "")),
                            html.escape(str(port_entry.get("ip") or "")),
                        ])
            parts.append(self._table_html(
                ["Port", "Protocol", "State", "Service", "Version", "IP"], rows
            ))
            parts.append("</section>")

        # Services
        if grouped["service"]:
            parts.append("<section>")
            parts.append("<h2>Services</h2>")
            rows = []
            for s in grouped["service"]:
                for svc in self._iter_service_detection_results(s):
                    rows.append([
                        str(svc.get("port")), html.escape(str(svc.get("service") or "")),
                        html.escape(str(svc.get("protocol") or "")),
                        html.escape(str(svc.get("banner") or "")[:80]),
                        html.escape(str(svc.get("version") or "")),
                        html.escape(str(svc.get("confidence") or "")),
                    ])
            parts.append(self._table_html(
                ["Port", "Service", "Protocol", "Banner", "Version", "Confidence"], rows
            ))
            parts.append("</section>")

        # DNS
        if grouped["dns"]:
            parts.append("<section>")
            parts.append("<h2>DNS Records</h2>")
            rows = []
            for d in grouped["dns"]:
                for rec in d.get("records", []):
                    rows.append([
                        html.escape(str(rec.get("record_type") or "")),
                        html.escape(str(rec.get("name") or "")),
                        html.escape(", ".join(rec.get("values", []) or [])),
                        str(rec.get("ttl") or ""),
                    ])
            parts.append(self._table_html(["Type", "Name", "Values", "TTL"], rows))
            parts.append("</section>")

        # WHOIS
        if grouped["whois"]:
            parts.append("<section>")
            parts.append("<h2>WHOIS</h2>")
            parts.append(self._kv_html(grouped["whois"]))
            parts.append("</section>")

        # SSL
        if grouped["ssl"]:
            parts.append("<section>")
            parts.append("<h2>SSL / TLS Analysis</h2>")
            parts.append(self._kv_html(grouped["ssl"]))
            parts.append("</section>")

        # HTTP
        if grouped["http"]:
            parts.append("<section>")
            parts.append("<h2>HTTP Security Headers</h2>")
            parts.append(self._http_html(grouped["http"]))
            parts.append("</section>")

        # Screenshots
        if grouped["screenshot"]:
            parts.append("<section>")
            parts.append("<h2>Screenshots</h2>")
            for s in grouped["screenshot"]:
                if s.get("captured"):
                    # Embed the screenshot PNG as a base64 data URI
                    # directly in the HTML.  This is the only approach
                    # that works reliably when the report is opened via
                    # a Blob URL (the current frontend flow) — a
                    # relative ``/api/v1/...`` URL cannot resolve against
                    # a Blob URL, and the browser cannot attach the JWT
                    # to a top-level navigation request.  Embedding the
                    # bytes makes the report fully self-contained and
                    # requires no further authentication to render the
                    # image.  The report itself is already served behind
                    # a signed short-lived token, so embedding the PNG
                    # bytes does not weaken security — anyone who can
                    # see this HTML is already authorised to see the
                    # scan results including the screenshot.
                    data_uri = self._screenshot_data_uri(s.get("screenshot_id"))
                    if data_uri:
                        parts.append(
                            f"<figure class='shot'><img src='{data_uri}' alt='screenshot'>"
                            f"<figcaption>{html.escape(str(s.get('url') or ''))}</figcaption></figure>"
                        )
                    else:
                        # File no longer on disk — show a placeholder
                        # note instead of a broken image link.
                        parts.append(
                            f"<figure class='shot'><div class='shot-missing'>"
                            f"Screenshot for {html.escape(str(s.get('url') or ''))} "
                            f"is no longer available on disk.</div></figure>"
                        )
            parts.append("</section>")

        # Errors / warnings
        if grouped["errors"]:
            parts.append("<section>")
            parts.append("<h2>Errors &amp; Warnings</h2>")
            parts.append("<ul class='errors'>")
            for err in grouped["errors"]:
                parts.append(
                    f"<li><strong>{html.escape(str(err.get('module') or ''))}:</strong> "
                    f"{html.escape(str(err.get('error') or ''))}</li>"
                )
            parts.append("</ul></section>")

        # Footer
        parts.append("<footer>")
        parts.append(f"<span>Basir Security Management System — Generated {now.isoformat(timespec='seconds')}</span>")
        parts.append(f"<span>Report ID: <code>{report_id}</code></span>")
        parts.append("</footer>")

        parts.append("</body></html>")
        return "".join(parts)

    # ---- PDF -----------------------------------------------------------
    async def generate_pdf(self, scan_id: int) -> bytes | None:
        scan, results = await self._gather(scan_id)
        if not scan:
            return None

        report_id = uuid.uuid4().hex
        now = datetime.now(timezone.utc)
        grouped = self._group_results(results)
        summary = self._build_summary(scan, grouped)
        generated_by = await self._get_username(scan.user_id)

        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
        )
        from reportlab.lib.enums import TA_LEFT, TA_CENTER

        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf, pagesize=A4,
            leftMargin=18 * mm, rightMargin=18 * mm,
            topMargin=18 * mm, bottomMargin=18 * mm,
            title=f"Basir Recon Report — {scan.target}",
        )

        styles = getSampleStyleSheet()
        h1 = ParagraphStyle("H1", parent=styles["Heading1"], textColor=colors.HexColor("#0ea5b7"), fontSize=20, spaceAfter=12)
        h2 = ParagraphStyle("H2", parent=styles["Heading2"], textColor=colors.HexColor("#0ea5b7"), fontSize=14, spaceAfter=8, spaceBefore=14)
        body = ParagraphStyle("Body", parent=styles["BodyText"], fontSize=10, leading=14, alignment=TA_LEFT)
        cover_title = ParagraphStyle("Cover", parent=styles["Title"], textColor=colors.HexColor("#0ea5b7"), fontSize=26, alignment=TA_CENTER, spaceAfter=18)
        cover_sub = ParagraphStyle("CoverSub", parent=styles["Normal"], fontSize=12, alignment=TA_CENTER, textColor=colors.HexColor("#666666"), spaceAfter=6)
        meta = ParagraphStyle("Meta", parent=styles["Normal"], fontSize=9, textColor=colors.HexColor("#888888"))
        mono = ParagraphStyle("Mono", parent=styles["Code"], fontSize=9, leading=12, textColor=colors.HexColor("#222222"))

        story: List[Any] = []

        # Cover
        story.append(Spacer(1, 50 * mm))
        story.append(Paragraph("Basir Security Management System", cover_sub))
        story.append(Paragraph("Network Reconnaissance Report", cover_title))
        story.append(Spacer(1, 10 * mm))
        story.append(Paragraph(f"<b>Target:</b> {html.escape(scan.target)}", cover_sub))
        story.append(Paragraph(f"<b>Scan ID:</b> #{scan.id}", cover_sub))
        story.append(Paragraph(f"<b>Status:</b> {scan.status}", cover_sub))
        story.append(Paragraph(f"<b>Generated by:</b> {html.escape(generated_by)}", cover_sub))
        story.append(Paragraph(f"<b>Report ID:</b> {report_id}", cover_sub))
        story.append(Paragraph(f"<b>Generated:</b> {now.isoformat(timespec='seconds')}", cover_sub))
        story.append(PageBreak())

        # Executive summary
        story.append(Paragraph("Executive Summary", h1))
        story.append(Paragraph(html.escape(summary), body))
        story.append(Spacer(1, 6))
        # Stats table
        stats_data = [
            ["Modules Run", ", ".join(scan.modules)],
            ["Progress", f"{scan.progress}%"],
            ["Started", scan.started_at.isoformat() if scan.started_at else "—"],
            ["Completed", scan.completed_at.isoformat() if scan.completed_at else "—"],
        ]
        stats_table = Table(stats_data, colWidths=[40 * mm, 130 * mm])
        stats_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#0d1224")),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#0ea5b7")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
            ("PADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(stats_table)

        # Target info
        story.append(Paragraph("Target Information", h2))
        story.append(Paragraph(
            f"<b>Target:</b> {html.escape(scan.target)}<br/>"
            f"<b>Type:</b> {html.escape(scan.target_type)}<br/>"
            f"<b>Modules:</b> {html.escape(', '.join(scan.modules))}<br/>"
            f"<b>Port preset:</b> {html.escape(scan.port_preset or 'default')}",
            body,
        ))

        # Host discovery
        if grouped["host_discovery"]:
            story.append(Paragraph("Host Discovery", h2))
            data = [["Host", "IP", "Hostname", "Status", "Latency (ms)"]]
            for h in grouped["host_discovery"]:
                data.append([
                    html.escape(str(h.get("host"))),
                    html.escape(str(h.get("ip") or "")),
                    html.escape(str(h.get("hostname") or "")),
                    html.escape(str(h.get("status") or "")),
                    html.escape(str(h.get("latency_ms") or "")),
                ])
            story.append(self._pdf_table(data, col_widths=[40 * mm, 35 * mm, 40 * mm, 25 * mm, 30 * mm]))

        # Open ports
        if grouped["port_scan"]:
            story.append(Paragraph("Open Ports", h2))
            data = [["Port", "Protocol", "State", "Service", "IP"]]
            for ps in grouped["port_scan"]:
                for p in self._iter_port_scan_results(ps):
                    if p.get("state") == "open":
                        data.append([
                            str(p.get("port")),
                            html.escape(str(p.get("protocol") or "tcp")),
                            html.escape(str(p.get("state") or "")),
                            html.escape(str(p.get("service_guess") or "")),
                            html.escape(str(p.get("ip") or "")),
                        ])
            if len(data) > 1:
                story.append(self._pdf_table(data, col_widths=[20 * mm, 25 * mm, 25 * mm, 40 * mm, 35 * mm]))

        # Services
        if grouped["service"]:
            story.append(Paragraph("Services", h2))
            data = [["Port", "Service", "Banner", "Version", "Confidence"]]
            for s in grouped["service"]:
                for svc in self._iter_service_detection_results(s):
                    data.append([
                        str(svc.get("port")),
                        html.escape(str(svc.get("service") or "")),
                        html.escape(str(svc.get("banner") or "")[:60]),
                        html.escape(str(svc.get("version") or "")),
                        html.escape(str(svc.get("confidence") or "")),
                    ])
            if len(data) > 1:
                story.append(self._pdf_table(data, col_widths=[15 * mm, 25 * mm, 60 * mm, 30 * mm, 25 * mm]))

        # DNS
        if grouped["dns"]:
            story.append(Paragraph("DNS Records", h2))
            data = [["Type", "Name", "Values", "TTL"]]
            for d in grouped["dns"]:
                for rec in d.get("records", []):
                    data.append([
                        html.escape(str(rec.get("record_type") or "")),
                        html.escape(str(rec.get("name") or "")),
                        html.escape(", ".join(rec.get("values", []) or [])[:80]),
                        str(rec.get("ttl") or ""),
                    ])
            if len(data) > 1:
                story.append(self._pdf_table(data, col_widths=[20 * mm, 40 * mm, 80 * mm, 25 * mm]))

        # WHOIS
        if grouped["whois"]:
            story.append(Paragraph("WHOIS", h2))
            story.append(self._pdf_kv(grouped["whois"]))

        # SSL
        if grouped["ssl"]:
            story.append(Paragraph("SSL / TLS Analysis", h2))
            story.append(self._pdf_kv(grouped["ssl"]))

        # HTTP
        if grouped["http"]:
            story.append(Paragraph("HTTP Security Headers", h2))
            data = [["Header", "Status", "Severity"]]
            for sh in grouped["http"].get("security_headers", []):
                data.append([
                    html.escape(str(sh.get("header") or "")),
                    "Present" if sh.get("present") else "Missing",
                    html.escape(str(sh.get("severity") or "")),
                ])
            if len(data) > 1:
                story.append(self._pdf_table(data, col_widths=[70 * mm, 40 * mm, 30 * mm]))

        # Screenshots — embed the actual PNG bytes into the PDF so the
        # report is self-contained and does not depend on the screenshot
        # retrieval API being reachable.
        if grouped["screenshot"]:
            story.append(Paragraph("Screenshots", h2))
            from reportlab.platypus import Image as RLImage
            from reportlab.lib.utils import ImageReader
            import os as _os
            for s in grouped["screenshot"]:
                if not s.get("captured"):
                    continue
                screenshot_id = s.get("screenshot_id")
                if not screenshot_id:
                    continue
                # Locate the file on disk
                shot_path = _os.path.join(
                    settings.RECON_SCREENSHOT_STORAGE_PATH,
                    f"{screenshot_id}.png",
                )
                if not _os.path.isfile(shot_path):
                    story.append(Paragraph(
                        f"<i>Screenshot for {html.escape(str(s.get('url') or ''))} "
                        f"is not available on disk.</i>",
                        body,
                    ))
                    continue
                try:
                    # Scale the image to fit the page width (max ~170mm)
                    img_reader = ImageReader(shot_path)
                    iw, ih = img_reader.getSize()
                    max_w = 170 * mm
                    max_h = 120 * mm
                    ratio = min(max_w / iw, max_h / ih)
                    story.append(Paragraph(
                        f"<b>URL:</b> {html.escape(str(s.get('url') or ''))}",
                        body,
                    ))
                    story.append(RLImage(shot_path, width=iw * ratio, height=ih * ratio))
                    story.append(Spacer(1, 6 * mm))
                except Exception as exc:  # noqa: BLE001
                    logger.warning(f"Failed to embed screenshot {screenshot_id} in PDF: {exc}")
                    story.append(Paragraph(
                        f"<i>Failed to embed screenshot: {html.escape(str(exc))}</i>",
                        body,
                    ))

        # Errors
        if grouped["errors"]:
            story.append(Paragraph("Errors & Warnings", h2))
            for err in grouped["errors"]:
                story.append(Paragraph(
                    f"<b>{html.escape(str(err.get('module') or ''))}:</b> "
                    f"{html.escape(str(err.get('error') or ''))}",
                    body,
                ))

        # Build the doc with a footer callback for page numbers
        def _footer(canvas, doc):
            canvas.saveState()
            canvas.setFont("Helvetica", 8)
            canvas.setFillColor(colors.HexColor("#888888"))
            canvas.drawString(18 * mm, 10 * mm, f"Basir Recon Report — Report ID: {report_id}")
            canvas.drawRightString(A4[0] - 18 * mm, 10 * mm, f"Page {doc.page}")
            canvas.restoreState()

        doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
        return buf.getvalue()

    # ---- metadata ------------------------------------------------------
    async def get_metadata(self, scan_id: int) -> Dict[str, Any] | None:
        scan = await self.scan_repo.get_by_id(scan_id)
        if not scan:
            return None
        generated_by = await self._get_username(scan.user_id)
        return {
            "scan_id": scan.id,
            "target": scan.target,
            "status": scan.status,
            "formats": ["html", "pdf"],
            "generated_by": generated_by,
            "created_at": scan.created_at.isoformat(),
            "completed_at": scan.completed_at.isoformat() if scan.completed_at else None,
        }

    # ------------------------------------------------------------------
    # Screenshot embedding helper — embeds the PNG file as a base64
    # data URI so the HTML report is fully self-contained and renders
    # correctly even when opened via a Blob URL (the current frontend
    # flow for ``fetchClientReportHtml`` / ``fetchScanReportHtml``).
    #
    # Returns ``None`` if the file is missing or unreadable.  Callers
    # MUST handle ``None`` by rendering a placeholder instead of a
    # broken <img src> link.
    # ------------------------------------------------------------------
    @staticmethod
    def _screenshot_data_uri(screenshot_id: Optional[str]) -> Optional[str]:
        if not screenshot_id:
            return None
        shot_path = os.path.join(
            settings.RECON_SCREENSHOT_STORAGE_PATH,
            f"{screenshot_id}.png",
        )
        try:
            with open(shot_path, "rb") as fh:
                raw = fh.read()
        except (OSError, FileNotFoundError):
            logger.warning(
                f"ReportService: screenshot file {shot_path} not found "
                f"or unreadable; rendering placeholder instead."
            )
            return None
        if not raw:
            logger.warning(f"ReportService: screenshot file {shot_path} is empty.")
            return None
        b64 = base64.b64encode(raw).decode("ascii")
        return f"data:image/png;base64,{b64}"

    # ------------------------------------------------------------------
    # Phase 17 — Client-level merged report
    # ------------------------------------------------------------------
    async def generate_client_html(self, client, scans: List[Scan]) -> str:
        """Merge every scan result row belonging to ``scans`` into a single
        HTML document grouped by section (hosts / ports / services / ...).
        """
        report_id = uuid.uuid4().hex
        now = datetime.now(timezone.utc)

        # Gather all results across scans
        all_results: List[ScanResult] = []
        for s in scans:
            fresh = await self.scan_repo.get_scan_with_results(s.id)
            if fresh:
                all_results.extend(fresh.results)
        all_results.sort(key=lambda r: r.created_at)
        grouped = self._group_results(all_results)

        parts: List[str] = []
        parts.append("<!DOCTYPE html>")
        parts.append("<html lang='en'><head><meta charset='utf-8'>")
        parts.append("<meta name='viewport' content='width=device-width, initial-scale=1'>")
        parts.append(f"<title>Basir Client Report — {html.escape(client.name)}</title>")
        parts.append("<style>")
        parts.append(self._html_css())
        parts.append("</style></head><body>")

        # Cover
        parts.append("<header class='cover'>")
        parts.append("<div class='brand'>Basir Security Management System</div>")
        parts.append("<h1>Client Reconnaissance Report</h1>")
        parts.append(f"<div class='meta'>Client: <code>{html.escape(client.name)}</code></div>")
        if client.company_name:
            parts.append(f"<div class='meta'>Company: <code>{html.escape(client.company_name)}</code></div>")
        if client.description:
            parts.append(f"<div class='meta'>{html.escape(client.description)}</div>")
        parts.append(f"<div class='meta'>Report ID: <code>{report_id}</code></div>")
        parts.append(f"<div class='meta'>Generated: {now.isoformat(timespec='seconds')}</div>")
        parts.append(f"<div class='meta'>Scans included: {len(scans)}</div>")
        parts.append("</header>")

        # Scan list
        parts.append("<section><h2>Included Scans</h2>")
        rows = [
            [f"#{s.id}", html.escape(s.target), html.escape(s.status),
             s.created_at.isoformat(timespec='seconds') if s.created_at else '',
             s.completed_at.isoformat(timespec='seconds') if s.completed_at else '']
            for s in scans
        ]
        parts.append(self._table_html(["Scan", "Target", "Status", "Created", "Completed"], rows))
        parts.append("</section>")

        # Sections
        if grouped["host_discovery"]:
            parts.append("<section><h2>Host Discovery</h2>")
            parts.append(self._table_html(
                ["Host", "IP", "Hostname", "Status", "Latency (ms)"],
                [[html.escape(str(h.get("host"))), html.escape(str(h.get("ip") or "")),
                  html.escape(str(h.get("hostname") or "")),
                  html.escape(str(h.get("status") or "")),
                  html.escape(str(h.get("latency_ms") or ""))] for h in grouped["host_discovery"]]
            ))
            parts.append("</section>")

        if grouped["port_scan"]:
            parts.append("<section><h2>Open Ports</h2>")
            rows = []
            for ps in grouped["port_scan"]:
                for p in self._iter_port_scan_results(ps):
                    if p.get("state") == "open":
                        rows.append([
                            str(p.get("port")), html.escape(str(p.get("protocol") or "tcp")),
                            html.escape(str(p.get("state") or "")),
                            html.escape(str(p.get("service_guess") or "")),
                            html.escape(str(p.get("ip") or "")),
                        ])
            parts.append(self._table_html(["Port", "Protocol", "State", "Service", "IP"], rows))
            parts.append("</section>")

        if grouped["service"]:
            parts.append("<section><h2>Services</h2>")
            rows = []
            for s in grouped["service"]:
                for svc in self._iter_service_detection_results(s):
                    rows.append([
                        str(svc.get("port")), html.escape(str(svc.get("service") or "")),
                        html.escape(str(svc.get("protocol") or "")),
                        html.escape(str(svc.get("banner") or "")[:80]),
                        html.escape(str(svc.get("version") or "")),
                        html.escape(str(svc.get("confidence") or "")),
                    ])
            parts.append(self._table_html(["Port", "Service", "Protocol", "Banner", "Version", "Confidence"], rows))
            parts.append("</section>")

        if grouped["dns"]:
            parts.append("<section><h2>DNS Records</h2>")
            rows = []
            for d in grouped["dns"]:
                for rec in d.get("records", []):
                    rows.append([
                        html.escape(str(rec.get("record_type") or "")),
                        html.escape(str(rec.get("name") or "")),
                        html.escape(", ".join(rec.get("values", []) or [])),
                        str(rec.get("ttl") or ""),
                    ])
            parts.append(self._table_html(["Type", "Name", "Values", "TTL"], rows))
            parts.append("</section>")

        if grouped["whois"]:
            parts.append("<section><h2>WHOIS</h2>")
            parts.append(self._kv_html(grouped["whois"]))
            parts.append("</section>")

        if grouped["ssl"]:
            parts.append("<section><h2>SSL / TLS Analysis</h2>")
            parts.append(self._kv_html(grouped["ssl"]))
            parts.append("</section>")

        if grouped["http"]:
            parts.append("<section><h2>HTTP Security Headers</h2>")
            parts.append(self._http_html(grouped["http"]))
            parts.append("</section>")

        # Screenshots — embed as base64 data URIs (same approach as the
        # scan-level HTML report) so the merged client report is also
        # self-contained and renders correctly when opened via a Blob URL.
        if grouped["screenshot"]:
            parts.append("<section><h2>Screenshots</h2>")
            for s in grouped["screenshot"]:
                if not s.get("captured"):
                    continue
                data_uri = self._screenshot_data_uri(s.get("screenshot_id"))
                if data_uri:
                    parts.append(
                        f"<figure class='shot'><img src='{data_uri}' alt='screenshot'>"
                        f"<figcaption>{html.escape(str(s.get('url') or ''))}</figcaption></figure>"
                    )
                else:
                    parts.append(
                        f"<figure class='shot'><div class='shot-missing'>"
                        f"Screenshot for {html.escape(str(s.get('url') or ''))} "
                        f"is no longer available on disk.</div></figure>"
                    )
            parts.append("</section>")

        if grouped["errors"]:
            parts.append("<section><h2>Errors &amp; Warnings</h2><ul class='errors'>")
            for err in grouped["errors"]:
                parts.append(
                    f"<li><strong>{html.escape(str(err.get('module') or ''))}:</strong> "
                    f"{html.escape(str(err.get('error') or ''))}</li>"
                )
            parts.append("</ul></section>")

        parts.append("<footer>")
        parts.append(f"<span>Basir Security Management System — Generated {now.isoformat(timespec='seconds')}</span>")
        parts.append(f"<span>Report ID: <code>{report_id}</code></span>")
        parts.append("</footer>")
        parts.append("</body></html>")
        return "".join(parts)

    # ---- helpers -------------------------------------------------------
    @staticmethod
    def _iter_port_scan_results(ps: Dict[str, Any]):
        """Yield individual port-entry dicts from a PORT_SCAN result row.

        The scan service persists PORT_SCAN rows as:
            {"scans": [{"host": str, "ip": str, "ports": [{"port", "state", ...}, ...]}, ...]}
        Older / simplified rows may store:
            {"ports": [{"port", "state", ...}, ...]}
        This helper accepts both shapes and yields each port dict with
        the ``ip`` and ``host`` fields propagated onto the port dict so
        callers can uniformly access ``p.get("ip")`` / ``p.get("host")``.
        """
        if not isinstance(ps, dict):
            return
        # Modern shape — one entry per scanned IP, each with its own ports list.
        scans = ps.get("scans")
        if isinstance(scans, list):
            for scan_entry in scans:
                if not isinstance(scan_entry, dict):
                    continue
                ip = scan_entry.get("ip")
                host = scan_entry.get("host")
                for p in scan_entry.get("ports", []) or []:
                    if not isinstance(p, dict):
                        continue
                    # Propagate ip/host onto the port dict (don't mutate original).
                    out = dict(p)
                    out.setdefault("ip", ip)
                    out.setdefault("host", host)
                    yield out
            return
        # Legacy shape — flat list of ports directly under "ports".
        ports = ps.get("ports")
        if isinstance(ports, list):
            for p in ports:
                if isinstance(p, dict):
                    yield dict(p)

    @staticmethod
    def _iter_service_detection_results(s: Dict[str, Any]):
        """Yield individual service-entry dicts from a SERVICE result row.

        Same shape contract as ``_iter_port_scan_results`` — accepts both
        the modern ``{"scans": [{...,"services":[...]}]}`` shape and the
        legacy ``{"services": [...]}`` shape.
        """
        if not isinstance(s, dict):
            return
        scans = s.get("scans")
        if isinstance(scans, list):
            for scan_entry in scans:
                if not isinstance(scan_entry, dict):
                    continue
                ip = scan_entry.get("ip")
                host = scan_entry.get("host")
                for svc in scan_entry.get("services", []) or []:
                    if not isinstance(svc, dict):
                        continue
                    out = dict(svc)
                    out.setdefault("ip", ip)
                    out.setdefault("host", host)
                    yield out
            return
        services = s.get("services")
        if isinstance(services, list):
            for svc in services:
                if isinstance(svc, dict):
                    yield dict(svc)

    def _group_results(self, results: List[ScanResult]) -> Dict[str, Any]:
        grouped: Dict[str, Any] = {
            "host_discovery": [],
            "port_scan": [],
            "service": [],
            "whois": {},
            "dns": [],
            "ssl": {},
            "http": {},
            "screenshot": [],
            "errors": [],
        }
        for r in results:
            key = r.result_type.lower()
            if key in ("host_discovery", "port_scan", "service", "dns", "screenshot"):
                grouped[key].append(r.data)
            elif key in ("whois", "ssl", "http"):
                grouped[key] = r.data
            if r.error:
                grouped["errors"].append({"module": r.result_type, "error": r.error})
        return grouped

    def _build_summary(self, scan: Scan, grouped: Dict[str, Any]) -> str:
        n_hosts = sum(len(h.get("hosts", [])) for h in grouped["host_discovery"])
        n_open = sum(
            1 for ps in grouped["port_scan"]
            for p in self._iter_port_scan_results(ps) if p.get("state") == "open"
        )
        n_dns = sum(len(d.get("records", [])) for d in grouped["dns"])
        created_str = scan.created_at.isoformat(timespec='seconds') if scan.created_at else "N/A"
        parts = [
            f"This report documents the reconnaissance scan performed against {scan.target} on "
            f"{created_str}.",
            f"The scan ran {len(scan.modules or [])} module(s) and finished with status {scan.status}.",
        ]
        if n_hosts:
            parts.append(f"Host discovery identified {n_hosts} host(s).")
        if n_open:
            parts.append(f"{n_open} open TCP port(s) were identified across scanned hosts.")
        if n_dns:
            parts.append(f"{n_dns} DNS record(s) were resolved.")
        return " ".join(parts)

    def _summary_stats_html(self, scan: Scan, grouped: Dict[str, Any]) -> str:
        n_hosts = sum(len(h.get("hosts", [])) for h in grouped["host_discovery"])
        n_open = sum(
            1 for ps in grouped["port_scan"]
            for p in self._iter_port_scan_results(ps) if p.get("state") == "open"
        )
        rows = [
            ("Modules Run", html.escape(", ".join(scan.modules))),
            ("Progress", f"{scan.progress}%"),
            ("Hosts Discovered", str(n_hosts)),
            ("Open Ports", str(n_open)),
            ("Started", scan.started_at.isoformat() if scan.started_at else "—"),
            ("Completed", scan.completed_at.isoformat() if scan.completed_at else "—"),
        ]
        return self._kv_html(dict(rows))

    def _target_info_html(self, scan: Scan) -> str:
        rows = {
            "Target": scan.target,
            "Type": scan.target_type,
            "Status": scan.status,
            "Modules": ", ".join(scan.modules),
            "Port preset": scan.port_preset or "default",
        }
        return self._kv_html(rows)

    def _kv_html(self, data: Dict[str, Any]) -> str:
        rows = "".join(
            f"<tr><th>{html.escape(str(k))}</th><td>{html.escape(str(v))}</td></tr>"
            for k, v in data.items() if v is not None and v != ""
        )
        return f"<table class='kv'>{rows}</table>"

    def _table_html(self, headers: List[str], rows: List[List[str]]) -> str:
        head = "".join(f"<th>{html.escape(h)}</th>" for h in headers)
        body_rows = "".join(
            "<tr>" + "".join(f"<td>{html.escape(c)}</td>" for c in row) + "</tr>"
            for row in rows
        )
        return f"<table class='data'><thead><tr>{head}</tr></thead><tbody>{body_rows}</tbody></table>"

    def _http_html(self, http: Dict[str, Any]) -> str:
        sh = http.get("security_headers") or []
        rows = []
        for h in sh:
            sev = h.get("severity") or "info"
            cls = f"badge {sev.replace(' ', '')}"
            status = "Present" if h.get("present") else "Missing"
            rows.append([
                html.escape(h.get("header") or ""),
                f"<span class='{cls}'>{status}</span>",
                html.escape(str(h.get("value") or "")[:80]),
                html.escape(sev),
            ])
        return self._table_html(["Header", "Status", "Value", "Severity"], rows)

    def _html_css(self) -> str:
        return """
        :root { --accent: #0ea5b7; --bg: #0d1224; --panel: #181f36; --text: #e6ebf5; --muted: #a1aecb; }
        * { box-sizing: border-box; }
        body { font-family: 'Inter', system-ui, -apple-system, sans-serif; background: var(--bg); color: var(--text); margin: 0; padding: 2rem; line-height: 1.5; }
        header.cover { background: linear-gradient(135deg, #0d1224 0%, #181f36 100%); border: 1px solid #2b3350; border-radius: 12px; padding: 2rem; margin-bottom: 2rem; }
        header.cover .brand { color: var(--accent); font-size: 0.9rem; text-transform: uppercase; letter-spacing: 2px; }
        header.cover h1 { margin: 0.5rem 0 1rem; font-size: 2rem; }
        .meta { color: var(--muted); font-size: 0.9rem; margin: 0.2rem 0; }
        code { background: #181f36; padding: 0.1rem 0.4rem; border-radius: 4px; font-family: 'JetBrains Mono', monospace; }
        section { background: rgba(24,31,54,0.6); border: 1px solid #2b3350; border-radius: 10px; padding: 1.5rem; margin-bottom: 1.5rem; }
        h2 { color: var(--accent); border-bottom: 1px solid #2b3350; padding-bottom: 0.5rem; margin-top: 0; }
        table { width: 100%; border-collapse: collapse; margin: 0.5rem 0; }
        table.data th, table.data td, table.kv th, table.kv td { border: 1px solid #2b3350; padding: 0.5rem; text-align: left; font-size: 0.85rem; }
        table.data th, table.kv th { background: #0d1224; color: var(--accent); text-transform: uppercase; font-size: 0.75rem; letter-spacing: 1px; }
        table.kv th { width: 30%; }
        .badge { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 999px; font-size: 0.75rem; }
        .badge.completed, .badge.good { background: rgba(16,185,129,0.2); color: #34d399; }
        .badge.failed, .badge.high { background: rgba(244,63,94,0.2); color: #fb7185; }
        .badge.running, .badge.medium { background: rgba(245,158,11,0.2); color: #fbbf24; }
        .badge.low, .badge.queued { background: rgba(34,211,238,0.15); color: #67e8f9; }
        .badge.info { background: rgba(161,174,203,0.2); color: #a1aecb; }
        ul.errors { color: #fb7185; }
        figure.shot { display: inline-block; margin: 1rem; text-align: center; }
        figure.shot img { max-width: 100%; border: 1px solid #2b3350; border-radius: 8px; }
        figure.shot figcaption { font-size: 0.8rem; color: var(--muted); margin-top: 0.5rem; }
        figure.shot .shot-missing { display: inline-block; padding: 1rem 1.5rem; border: 1px dashed #2b3350; border-radius: 8px; color: var(--muted); font-size: 0.85rem; font-style: italic; }
        footer { text-align: center; color: var(--muted); font-size: 0.8rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #2b3350; display: flex; justify-content: space-between; }
        """

    # ---- PDF helpers ---------------------------------------------------
    def _pdf_table(self, data: List[List[str]], col_widths: List[float]):
        from reportlab.platypus import Table, TableStyle
        from reportlab.lib import colors
        t = Table(data, colWidths=col_widths, repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0d1224")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0ea5b7")),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#cccccc")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("PADDING", (0, 0), (-1, -1), 4),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f4f7fb")]),
        ]))
        return t

    def _pdf_kv(self, data: Dict[str, Any]):
        from reportlab.platypus import Table, TableStyle
        from reportlab.lib import colors
        from reportlab.lib.units import mm
        rows = []
        for k, v in data.items():
            if v is None or v == "":
                continue
            if isinstance(v, (list, dict)):
                v_str = ", ".join(str(x) for x in v) if isinstance(v, list) else str(v)
            else:
                v_str = str(v)
            rows.append([html.escape(str(k)), html.escape(v_str[:200])])
        t = Table(rows, colWidths=[45 * mm, 130 * mm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#0d1224")),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#0ea5b7")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#cccccc")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("PADDING", (0, 0), (-1, -1), 4),
        ]))
        return t
